# Utiliser l'image PHP avec Apache comme image de base
FROM php:8.0-apache

# Installer les dépendances requises pour GD, PDO et PDO MySQL
RUN apt-get update && \
    apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev && \
    docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install gd pdo pdo_mysql

# Copie de fichiers de configuration ou de scripts si nécessaire
COPY simple_apache_data/ /var/www/html/

# Exposer le port 80
# EXPOSE 80
