version: "3.8"

services:
  # Serveur MariaDB
  db:
    image: mariadb:10.5
    container_name: mariadb_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./init/init_logs.cnf:/etc/mysql/conf.d/init_logs.cnf
      - ./logs/mysql:/var/log/mysql
    networks:
      - wp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serveur web Apache (WordPress)
  wordpress:
    image: wordpress:php8.0-apache
    container_name: wordpress_app
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
    volumes:
      - ./wp-data:/var/www/html
      - ./logs/apache:/var/log/apache2
    ports:
      - "8080:80"
    networks:
      - wp-network
    depends_on:
      db:
        condition: service_healthy

  # Service Ruby pour le stockage des logs
  log_storer:
    build:
      context: .
      dockerfile: Dockerfile_log_storer
    container_name: log_storer
    volumes:
      - ./scripts_rb:/usr/src/app
    working_dir: /usr/src/app
    command: ruby store_logs.rb
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "ruby", "-e", "require 'socket'; TCPSocket.new('localhost', 12345)"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - wp-network

  # Service Ruby pour la collecte des logs
  log_collector:
    build:
      context: .
      dockerfile: Dockerfile_log_collector
    container_name: log_collector
    volumes:
      - ./scripts_rb:/usr/src/app
      - ./logs/apache:/var/log/apache2
      - ./logs/mysql:/var/log/mysql
    working_dir: /usr/src/app
    command: ruby collect_logs.rb
    depends_on:
      log_storer:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - wp-network

volumes:
  db-data:
    driver: local

networks:
  wp-network:
    driver: bridge

